[
  { 'name'     : 'englishvariant',
    'pattern'  : '/*path',
    'view'     : 'staticfile',
    'language' : 'en', 
    'content_coding' : 'gzip',
    'rootloc'  : '/home/pratap/dev/netscale/pluggdapps/sphinxdoc/build/html/',
  },
  { 'name'     : 'frenchvariant',
    'pattern'  : '/*path',
    'view'     : 'staticfile',
    'language' : 'fr', 
    'content_coding' : 'gzip',
    'rootloc'  : '/home/pratap/tmp/pluggdapps-fr/',
  },
]
